import type { Match } from '../data/footballData';
const VERSION=2; const MAX_PAYLOAD=16*1024;
function safe(m:Match,includeContributions=false){if(m.visibility==='PRIVATE')throw new Error('Private matches cannot be publicly shared.');const base={v:VERSION,type:m.type,team1:String(m.team1).slice(0,120),team2:String(m.team2).slice(0,120),title:m.title?String(m.title).slice(0,160):undefined,score1:Number(m.score1)||0,score2:Number(m.score2)||0,status:m.status,dateLabel:String(m.dateLabel||'').slice(0,100),dateKey:Number(m.dateKey),stadium:m.stadium?String(m.stadium).slice(0,120):undefined,city:m.city?String(m.city).slice(0,120):undefined,time:m.time?String(m.time).slice(0,10):undefined,story:m.story?String(m.story).slice(0,500):undefined,visibility:'PUBLIC'};if(includeContributions&&m.playerContributions){return{...base,playerContributions:{team1:m.playerContributions.team1.slice(0,5).map(p=>({playerName:String(p.playerName).slice(0,60),goals:Number(p.goals)||0,assists:Number(p.assists)||0})),team2:m.playerContributions.team2.slice(0,5).map(p=>({playerName:String(p.playerName).slice(0,60),goals:Number(p.goals)||0,assists:Number(p.assists)||0}))}}}return base}
function encode(raw:string){const bytes=new TextEncoder().encode(raw);let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replaceAll('+','-').replaceAll('/','_').replaceAll('=','')}
function decode(payload:string){const pad=payload+'='.repeat((4-payload.length%4)%4);const bin=atob(pad.replaceAll('-','+').replaceAll('_','/'));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}
export function encodeMatchShare(m:Match,options?:{includeContributions?:boolean}){const token=encode(JSON.stringify(safe(m,options?.includeContributions)));if(token.length>MAX_PAYLOAD)throw new Error('Share payload too large');return token}
export function decodeMatchShare(payload:string):Partial<Match>|null{try{if(!payload||payload.length>MAX_PAYLOAD)return null;const x=JSON.parse(decode(payload));if(x.v!==VERSION||x.visibility!=='PUBLIC'||typeof x.team1!=='string'||typeof x.team2!=='string'||!Number.isFinite(x.dateKey))return null;return x}catch{return null}}
export async function shareMatch(m:Match,options?:{includeContributions?:boolean}){const url=`${location.origin}/share/match/${encodeMatchShare(m,options)}`;if(navigator.share){await navigator.share({title:`${m.team1} × ${m.team2}`,text:m.title||'TAAMEN match',url});return 'shared'}if(navigator.clipboard)await navigator.clipboard.writeText(url);return 'copied'}
export function matchShareSvg(m:Match){const title=m.title||`${m.team1} × ${m.team2}`;return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#193940"/><stop offset="1" stop-color="#0c2025"/></linearGradient></defs><rect width="1200" height="630" rx="48" fill="url(#g)"/><circle cx="1030" cy="110" r="120" fill="#9BF272" opacity=".08"/><text x="120" y="100" fill="#BAC8D9" font-family="Arial" font-size="28">TAAMEN 2.0</text><text x="600" y="190" text-anchor="middle" fill="#9BF272" font-family="Arial" font-size="34">${escapeXml(String(m.type).toUpperCase())}</text><text x="600" y="300" text-anchor="middle" fill="#fff" font-family="Arial" font-size="56" font-weight="700">${escapeXml(title)}</text><text x="600" y="390" text-anchor="middle" fill="#fff" font-family="Arial" font-size="48">${escapeXml(m.team1)}  ${m.status==='FINISHED'||m.status==='انتهت'?`${m.score1} : ${m.score2}`:'VS'}  ${escapeXml(m.team2)}</text><text x="600" y="475" text-anchor="middle" fill="#BAC8D9" font-family="Arial" font-size="28">${escapeXml(m.dateLabel)}${m.time?` · ${escapeXml(m.time)}`:''}${m.stadium?` · ${escapeXml(m.stadium)}`:''}</text><text x="600" y="545" text-anchor="middle" fill="#7ABF5A" font-family="Arial" font-size="22">PUBLIC SHARE</text></svg>`}
function escapeXml(s:string){return s.replace(/[<>&'"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]!))}
export function downloadMatchImage(m:Match){const blob=new Blob([matchShareSvg(m)],{type:'image/svg+xml'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`taamen-${m.id}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
